import '../styles/globals.css'
import Head from 'next/head'
import Nav from './components/Nav'
import Footer from './components/Footer'

function MyApp({ Component, pageProps }) {
  return (
    <>
    
    <Head>
        <title>Restarant NAME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='body-bg'>
    </div>

    <Nav />
    <Component {...pageProps} />
    <Footer />
    </>

  )
}

export default MyApp
